name: Deploy Django App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Build 
      run : docker build -t thingsx/thingsx_project:latest .

    - name: Run
      run: docker compose down && docker compose up -d